services:
  metaboanalystr4:
    image: benson1231/metaboanalystr:v1
    container_name: metaboanalystr4
    working_dir: /workspace
    volumes:
      - ./scripts:/workspace/scripts
      - ./results:/workspace/results
    tty: true
    stdin_open: true
    command: ["/bin/bash"]