name: Metabolomics Test

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: Build/Prepare Docker Service
        run: docker compose pull || true

      - name: Run introduction.R
        run: |
          docker compose run --rm metaboanalystr4 \
            Rscript scripts/introduction.R

      - name: Run read_data.R
        run: |
          docker compose run --rm metaboanalystr4 \
            Rscript scripts/read_data.R
